[package]
name = "wasmer-engines"
version = "1.1.0"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2018"
description = "Engines and sibling types for the `wasmer-*-python` crates"
readme = "README.md"
repository = "https://github.com/wasmerio/wasmer-python"
keywords = ["python", "extension", "webassembly"]
categories = ["wasm"]
publish = false

[dependencies]
wasmer = { version = "2.1.1", default-features = false, features = ["wat", "universal", "dylib", "compiler"] }
wasmer-compiler = "2.1.1"
pyo3 = { version = "0.18", features = ["extension-module"] }
enumset = "1.0.6"
