[package]
name = "wasmer_engines"
version = "1.0.0-beta2"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2018"
description = "Engines and sibling types for the `wasmer-*-python` crates"
readme = "README.md"
repository = "https://github.com/wasmerio/wasmer-python"
keywords = ["python", "extension", "webassembly"]
categories = ["wasm"]
publish = false

[dependencies]
wasmer = { git = "https://github.com/wasmerio/wasmer", branch = "master", default-features = false, features = ["wat", "jit", "native", "compiler"] }
wasmer-compiler = { git = "https://github.com/wasmerio/wasmer", branch = "master" }
#pyo3 = { version = "0.13", features = ["extension-module"] }
pyo3 = { git = "https://github.com/Hywan/pyo3", branch = "fix-cross-compil", features = ["extension-module"] }
wasmer_enumset = "1.0"