[package]
name = "wasmer_engines"
version = "1.0.0"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2018"
description = "Engines and sibling types for the `wasmer-*-python` crates"
readme = "README.md"
repository = "https://github.com/wasmerio/wasmer-python"
keywords = ["python", "extension", "webassembly"]
categories = ["wasm"]
publish = false

[dependencies]
wasmer = { version = "2.0.0", default-features = false, features = ["wat", "jit", "native", "compiler"] }
wasmer-compiler = "1.0.2"
pyo3 = { version = "0.13", features = ["extension-module"] }
enumset = "1.0.4"