name: Build and Test

on:
  push:
    branches:
      - master
      - staging
      - trying
      - 'prepare-*'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build and Test

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        target:
          - id: 'linux-amd64'
            os: 'ubuntu-18.04'
            target-name: 'x86_64-unknown-linux-gnu'
            rust-toolchain: 'stable'
            llvm-archive-url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/10.x/linux-amd64.tar.gz'

          - id: 'linux-aarch64'
            os: ['self-hosted', 'linux', 'ARM64']
            target-name: 'aarch64-unknown-linux-gnu'
            rust-toolchain: 'nightly'
            llvm-archive-url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/10.x/linux-aarch64.tar.gz'

          - id: 'darwin-amd64'
            os: 'macos-latest'
            target-name: 'x86_64-apple-darwin'
            rust-toolchain: 'stable'
            llvm-archive-url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/10.x/darwin-amd64.tar.gz'

          - id: 'windows-amd64'
            os: 'windows-latest'
            target-name: 'x86_64-pc-windows-msvc'
            rust-toolchain: 'stable'
            llvm-archive-url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/10.x/windows-amd64.tar.gz'
      fail-fast: true

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.target.rust-toolchain }}
          default: true
          override: true
          profile: minimal
          target: ${{ matrix.target.target-name }}

      - uses: Swatinem/rust-cache@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Fake `pyenv` installation
        shell: bash
        run: |
          echo "${{ matrix.python }}" > .python-version

      - name: Set up LLVM for `wasmer_compiler_llvm`
        if: matrix.target.id != 'windows-amd64'
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL ${{ matrix.target.llvm-archive-url }} -o llvm.tar.gz
          mkdir -p ${{ env.LLVM_DIR }}
          tar xzvf llvm.tar.gz -C ${{ env.LLVM_DIR }}
          echo ${{ env.LLVM_DIR }}/bin >> $GITHUB_PATH
        env:
          LLVM_DIR: ${{ github.workspace }}/llvm

      - name: Set up utilities
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          test -f $HOME/.cargo/bin/just || cargo install just
          test -f $HOME/.cargo/bin/fd || cargo install fd-find

      - name: Set up utilities  (macOS)
        if: matrix.target.id == 'darwin-amd64'
        shell: bash
        run: |
          brew install gnu-sed

      - name: Set build number
        if: startsWith(github.ref, 'refs/heads/prepare-')
        shell: bash
        run: |
          scripts/update-version.sh "$(scripts/update-version.sh --get)-${{ github.run_id }}"

      - name: Prelude
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          just prelude

      - name: Compile the library
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          maturin list-python
          PYTHON_INTERPRETER=$(maturin list-python | grep -o "CPython $(cat .python-version | grep -o -E '^[^\.]+\.[^\.]+').* at .*" | cut -d' ' -f 4 | tr '\\' '/')
          echo "Selected interpreter: ${PYTHON_INTERPRETER}"
          just build-all "${{ matrix.target.target-name }}"

      - name: Run all the tests
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          just test

      - name: Build the wheels
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          maturin list-python
          PYTHON_INTERPRETER=$(maturin list-python | grep -o "CPython $(cat .python-version | grep -o -E '^[^\.]+\.[^\.]+').* at .*" | cut -d' ' -f 4 | tr '\\' '/')
          echo "Selected interpreter: ${PYTHON_INTERPRETER}"
          just build-all-wheels "${PYTHON_INTERPRETER}" "${{ matrix.target.target-name }}"
          just build-any-wheel

      - name: Inspect wheels
        shell: bash
        run: |
          ls -lhaGiR target/wheels/*.whl

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.python }}-${{ matrix.target.id }}
          path: target/wheels
          if-no-files-found: error
          retention-days: 1

  prerelease:
    name: Pre-Release

    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/heads/prepare-')

    needs: [test]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download the Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Inspect artifacts
        shell: bash
        run: |
          ls -lhaGiR artifacts/*

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Fake `pyenv` installation
        shell: bash
        run: |
          echo "3.9" > .python-version

      - uses: Swatinem/rust-cache@v1

      - name: Set up just
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/3.9/bin:$PATH"
          test -f $HOME/.cargo/bin/just || cargo install just

      - name: Prelude
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/3.9/bin:$PATH"
          just prelude

      - name: Publish the wheels on TestPyPI
        shell: bash
        env:
          TWINE_PASSWORD: ${{ secrets.MATURIN_PASSWORD }}
        run: |
          export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/3.9/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          just publish testpypi artifacts/wheels-*/*.whl
